name: breeds_widget
description: "Package of widget for breeds APP."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_lints: ^3.0.0
  carousel_slider: ^5.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  gap: ^3.0.1
  google_fonts: ^6.1.0
  internet_connection_checker: ^1.0.0+1

  connectivity_plus: ^6.1.3
  # connectivity_plus: ^5.0.1
  # l10n_breeds:
  #   path: ../l10n_breeds
  # utils_breeds:
  #   path: ../utils_breeds
  # models_breeds:
  #   path: ../models_breeds
  l10n_breeds:
    git:
      url: https://github.com/wilver06w/l10n_breeds.git
      ref: main
  utils_breeds:
    git:
      url: https://github.com/wilver06w/utils_breeds.git
      ref: main
  models_breeds:
    git:
      url: https://github.com/wilver06w/models_breeds.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1
# The following section is specific to Flutter packages.
flutter:
